version: '2.1'

services:
  em-annotation-app:
    build:
      context: .
#    image: hmcts/em-annotation-app:latest
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://annotation-app-db:5432/em-annotation-app
      - SPRING_DATASOURCE_USERNAME=em-annotation-app
      - SPRING_DATASOURCE_PASSWORD=em-annotation-app
      - IDAM_USER_BASE_URI=http://idam-api:8080
      - OPEN_ID_API_BASE_URI=https://idam-api.aat.platform.hmcts.net/o
      - OIDC_ISSUER_BASE_URI=https://forgerock-am.service.core-compute-idam-aat.internal:8443/openam/oauth2/hmcts
      - IDAM_S2S_BASE_URI=http://service-auth-provider-api:8080
      - APPINSIGHTS_INSTRUMENTATIONKEY=test_app
    # these environment variables are used by java-logging library
      - ROOT_APPENDER=JSON_CONSOLE
      - JSON_CONSOLE_PRETTY_PRINT=false
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=em-annotation-app
      - REFORM_TEAM=em-annotation
      - REFORM_ENVIRONMENT=docker
    links:
     - annotation-app-db
    depends_on:
     - annotation-app-db
    ports:
    - $SERVER_PORT:8080

  annotation-app-db:
    image: postgres
    environment:
     - POSTGRES_USER=em-annotation-app
     - POSTGRES_PASSWORD=em-annotation-app
     - POSTGRES_DB=em-annotation-app
    ports:
     - 5433:5432

